version: '3'
services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: jpatest
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
